name: phone_text_field
description: A comprehensive Flutter plugin for international phone number input, validation, formatting, and country selection with localization support.
version: 2.0.0
homepage: https://github.com/MohamedAbd0/phone_text_field
repository: https://github.com/MohamedAbd0/phone_text_field
issue_tracker: https://github.com/MohamedAbd0/phone_text_field/issues
documentation: https://github.com/MohamedAbd0/phone_text_field#readme

topics:
  - phone
  - textfield
  - validation
  - internationalization
  - country-picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
